### ISSUE TITLE
Feature Request: Ability to specify date formats

### ISSUE THREAD

**Issue by ghost** [sanity-io/sanity-plugin-scheduled-publishing#11]
The DATE_FORMAT object defined in `src/constants.tsx` specifies the date-fns date formats used in the plugin's UI.  It would be helpful if one could configure these formats without modifying the plugin source code.  In my case, the US commonly uses MM/DD/YYYY format, and it is confusing for users to switch to DD/MM/YYYY when scheduling content.

![Screen Shot 2022-05-06 at 10 41 05 AM](https://user-images.githubusercontent.com/94555437/167182865-bfcc1686-3a92-4702-be57-6eeb4a11f221.png)

**Comment by robinpyon** [comment]
This is now possible as of `1.3.0` –

```
  plugins: [
    scheduledPublishing({
      // E.g. 12/25/2000 6:30 AM
      inputDateTimeFormat: 'MM/dd/yyyy h:mm a',
    })
  ],
```

Where `inputDateTimeFormat` is a valid [date-fns format token](https://date-fns.org/docs/format).

Note that this only applies to the above input field – other display-only dates remain as-is for now.
