### ISSUE TITLE
Schedule date and time picker

### ISSUE THREAD

**Issue by Bradzerafa** [sanity-io/sanity-plugin-scheduled-publishing#12]
Hi, 
Are we able to limit / not allow someone scheduling a document with the current time or if the time has already passed. I noticed this has been implemented for the date but i can still do it for the time and it errors with a vague error.

For example if its currently 9/5/22 10:55am, they shouldn't be able to try and schedule a time before 10:55am or the current time

![Screen Shot 2022-05-09 at 10 59 30 am](https://user-images.githubusercontent.com/29835518/167323825-f7669ce6-60b0-4093-b032-764276b1fb9b.png)

**Comment by robinpyon** [comment]
Hey @Bradzerafa, this should be fixed in the latest release (`0.1.9`)

Date validation should now correctly trigger on changes to both input field and calendar date picker (including time). 

A future update will also improve messaging on these error notifications too.
