### ISSUE TITLE
Unable to retrieve schedules in Safari

### ISSUE THREAD

**Issue by frederikgdl** [sanity-io/sanity-plugin-scheduled-publishing#25]
**Describe the bug**

When I try to schedule a document or when I open the Schedules tool in Safari it says `Something went wrong, unable to retrieve schedules.
More information in the developer console.`
I can see I have a request to `.../features/scheduledPublishing` that responds with
```
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "A valid session is required for this endpoint"
}
```
It works normally in Chrome.

**Which versions of Sanity are you using?**

@sanity/cli                   2.34.0 (up to date)
@sanity/base                  2.34.0 (up to date)
@sanity/cli                   2.34.0 (up to date)
@sanity/components            2.14.0 (up to date)
@sanity/core                  2.34.0 (up to date)
@sanity/default-layout        2.34.0 (up to date)
@sanity/default-login         2.34.0 (up to date)
@sanity/desk-tool             2.34.0 (up to date)
@sanity/eslint-config-studio   2.0.0 (up to date)
@sanity/production-preview    2.33.2 (up to date)
@sanity/scheduled-publishing  0.1.12 (up to date)
@sanity/vision                2.34.0 (up to date)

**What operating system are you using?**
macOS Monterey Version 12.6

**Which versions of Node.js / npm are you running?**
8.5.5
v16.17.0

**Comment by robinpyon** [comment]
Thanks for flagging this @frederikgdl

The plugin wasn't correctly inferring the current auth token in when using cookieless auth (e.g. in Safari), this should now be resolved in `0.1.13`. Please shout if you have any other issues here!
