### ISSUE TITLE
Compatibility issue with Sanity Studio v3.14.4

### ISSUE THREAD

**Issue by psntr** [sanity-io/sanity-plugin-scheduled-publishing#80]
As the title says, I run into an issue with the latest version of Sanity Studio and this plugin.

`✘ [ERROR] No matching export in "node_modules/sanity/lib/index.esm.js" for import "ValidationList"

    node_modules/@sanity/scheduled-publishing/lib/index.esm.js:1:2359:
      1 │ ...eSchema as H,isValidationErrorMarker as U,isValidationWarningMarker as Z,ValidationList as _,useValidationStatus as X,useDocumentPreviewStore as Y,InsufficientP...
        ╵   `
        
```
error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@sanity/scheduled-publishing/lib/index.esm.js:1:2359: ERROR: No matching export in "node_modules/sanity/lib/index.esm.js" for import "ValidationList"
```

A bit too abstract to fully understand what to do, so far I have to disable the plugin, anyone else encounter this issue?

**Comment by rexxars** [comment]
Thanks for reporting - please upgrade to `1.2.0` or a fix!
