### ISSUE TITLE
Date picker not rendering as of 1.2.1

### ISSUE THREAD

**Issue by leighkendell** [sanity-io/sanity-plugin-scheduled-publishing#87]
The date picker that renders within the document actions doesn't pop up consistently or at all, likely introduced via the [change](https://github.com/sanity-io/sanity-plugin-scheduled-publishing/commit/06d3d0efeb894d44bf0722b7b8f94f0716bb1e98) that went into 1.2.1 around rendering. Rolling back to 1.2.0 seems to fix this.

<img width="683" alt="image" src="https://github.com/sanity-io/sanity-plugin-scheduled-publishing/assets/765486/3e38d100-7cb4-4b10-8d81-1f44f542cd0a">

**Comment by sturtus** [comment]
Bump. Same behavior in 3.16.7

**Comment by SILVIA-VECEK-Movember** [comment]
We have the same issue where certain screen sizes hides the date picker completely. Rolling back to v1.2.0 fixes this issue

**Comment by robinpyon** [comment]
Thanks for reporting – I believe this issue was addressed in [1.2.2](https://github.com/sanity-io/sanity-plugin-scheduled-publishing/releases/tag/v1.2.2). 

Please give that a try and do shout if you're still experiencing issues.
