### ISSUE TITLE
Failed to run: unknown token type

### ISSUE THREAD

**Issue by corygibbons** [sanity-io/sanity-plugin-scheduled-publishing#9]
Installed the plugin and everything seems to work well until the scheduled publish time happens, at which point I get the following error:

```
This schedule failed to run.

execution failed: {"error":{"description":"unknown token type \"\"","type":"httpBadRequest"}}
```

Seems to happen for every scheduled document.

Team plan, Studio is on `v2.29.8`, private dataset, and I'm an admin user.

**Comment by tillschweneker** [comment]
Same here. Non-Profit Plan, Studio version `2.29.8`, private dataset and admin user

**Comment by robinpyon** [comment]
@corygibbons @tillschweneker 

Thanks for raising this – we're currently aware of schedule error messages not being super helpful right now.

I'm also able to repro this issue – even with simple schedules that shouldn't otherwise fail. We're investigating and will get back here shortly.

**Comment by robinpyon** [comment]
I can confirm this issue has since been fixed – please do let us know if you continue to have issues here!

**Comment by corygibbons** [comment]
Thanks @robinpyon, seems to be working well now 🎉
